/* =====================================================
   KONFIG — EDIT DI SINI
   ===================================================== */
const EVENT_DATE_STR = '2026-09-20T19:20:00+07:00'; // tanggal malam penganugerahan
const LS_KEY = 'boysAwards_me_v3'; // data pribadi perangkat ini

/* ====== ANGGOTA OTB — GANTI NAMA + USERNAME KALIAN ====== */
const ROSTER = [
    { name: 'Angga Pratama', usn: 'AngPrata' },
    { name: 'Kala', usn: 'd1kalahujan' },
    { name: 'Adam', usn: 'gubergnurr' },
    { name: 'Mayong (Xenon)', usn: 'fuckpjuh' },
    { name: 'Aan', usn: 'Pfraksi' },
    { name: 'Keano', usn: 'qampunhk' },
    { name: 'Shieza', usn: 'snoopyeaye' },
    { name: 'Jeremy', usn: 'peng3dr' },
    { name: 'Mas Dacil', usn: 'siDaciL' },
    { name: 'Abing Faker', usn: 'cpengocokk' },
    { name: 'Travis. كالْدير', usn: 'qPrampok' },
    { name: 'Haqi صدام', usn: 'iCRlMlNAL' },
    { name: 'A. بايلشميت', usn: 'cBastaard' },
    { name: 'Jovan', usn: 'ruthIessx' },
    { name: 'Alan¹⁹⁸⁹', usn: 'Usrm4n' },
    { name: 'Zidan', usn: 'zydnll' },
    { name: 'Kananta @BolehNaksir', usn: 'Almondbabybigbboy' },
    { name: 'Sebastian.', usn: 'seanBandungb' },
    { name: 'ju(pres)iden', usn: 'grrydenn' },
    { name: 'Bengky', usn: 'geminianjing' },
    { name: 'Venn', usn: 'bulvzit' },
    { name: 'J, Marco', usn: 'egysl' },
    { name: 'Asthon Hillmi wschäl', usn: 'ashotgaf' },
    { name: 'Daniel V\'Hoover', usn: 'Nilhoov' },
    { name: 'Kenneth', usn: 'Antiheruo' },
    { name: 'Johnathan C.', usn: 'Jhncdne' },
    { name: 'Kelvin, D', usn: 'seonghyeonreall' },
    { name: 'Arsenanda R.', usn: 'Lkomandann' },
    { name: 'Javier Desmond.', usn: 'Qbasict' },
    { name: 'Jace C.', usn: 'smotief' },
    { name: 'H\' Sajagat السيد', usn: 'iPejantanh' },
    { name: 'Ragasa D. @BolehCium', usn: 'nerv_car' },
    { name: 'Hades', usn: 'fdeathsoul' },
    { name: 'sachio basteen', usn: 'oAdorabble' },
    { name: 'Zachary', usn: 'afterhaz' },
    { name: 'Kaisan', usn: 'iPembelort' },
    { name: 'Zach', usn: 'NL0SH' },
    { name: 'CASHELIO.', usn: 'cSpawn' },
    { name: 'Jev', usn: 'ROOCKST14R' },
    { name: 'Jeremiah', usn: 'iLondonnn' },
    { name: 'LSKRC. Skylar Tzy', usn: 'jjshakel' },
    { name: 'resha jahat', usn: 'iLucied' },
    { name: 'Tama @sceminar', usn: 'Sceminar' },
    { name: 'mavarosé.', usn: 'yeatao' },
    { name: 'Bimo', usn: 'angrybim' },
    { name: 'Jalu ntik', usn: 'Presiden19' },
    { name: 'William', usn: 'wiLdercove' },
    { name: 'Leon, Only reply cf.', usn: 'jvkEleon' },
    { name: 'Zavier @BolehNaksir', usn: 'iPec1ntaB0kp' },
    { name: 'J.V texän', usn: 'iCHOI_VJ' },
    { name: 'yunhO', usn: 'yunhoimut' },
    { name: 'Roger', usn: 'Chaotci' },
    { name: '+1 Kyle Dawson', usn: 'wKonocortis' },
    { name: 'PRASS AMNESIA', usn: 'Dantelaso' },
    { name: 'Kãfka كافكا', usn: 'Kafksamudra' },
    { name: 'Mars', usn: 'Religionistt' },
    { name: '@___juviell 🐈‍⬛💗', usn: 'tueelips' },
    { name: 'Saad', usn: 'wbajar' },
    { name: 'Jean Alderic___⚙️ #UNSCANEXT03', usn: 'iJeanaldrc' },
    { name: 'Sadipta Alaskar Pradipta', usn: 'iPAnakBandung' },
    { name: 'Cave, milo bingung pake muse apa', usn: 'tserpanah' },
    { name: 'Levi, A.', usn: 'lLeviackermanx' },
    { name: 'Seno Adipati', usn: 'sensadip' },
    { name: 'Steve, Jonathan', usn: 'stxvey' },
    { name: 'Ryxan', usn: 'ryxxan' },
    { name: 'V\'SPIDΞY 9૯ Alandraa มิลาน', usn: 'miloOkeandra' },
    { name: 'aru', usn: 'niskasla' },
    { name: 'GARRÉTZ غاريتز', usn: 'xmarllborro' },
    { name: 'Kaiven', usn: 'vHotnive' },
    { name: 'Elio', usn: 'kael_ioo' },
    { name: 'Brykh', usn: 'Keonhju' },
    { name: 'وسيم', usn: 'yagantebgg' },
    { name: '—Vitto Daniel 🎸', usn: 'pitobrengsek' },
    { name: 'Kavin SetBoy #2k26 set sedih😔🌙', usn: 'Kgntgan' },
    { name: 'Gathan', usn: 'papajahatgp3' },
    { name: 'Samuel erlga DON’T PANIC', usn: 'samuelxh' },
    { name: 'Arham Ali', usn: 'ArrhamAli' },
    { name: 'Bimo', usn: 'kntllbpkmu' },
    { name: 'Kale. #semi-ia', usn: 'kingzkale' },
    { name: 'Kaiverth, J. ⭐ — ', usn: 'sghyeonZ' },
    { name: 'Jaretro', usn: 'retplak' },
    { name: 'Rama', usn: 'iNgaseng' },
    { name: 'Zayne', usn: 'zynczy' },
    { name: 'Divon Morgan.', usn: 'CAROLLUS' },
    { name: 'Kayess    Èlysshia', usn: 'mKayyes' },
    { name: 'Sam wschäl', usn: 'ssamuudraa' },
    { name: 'Harsa', usn: 'hheatwavee' },
    { name: 'Seann', usn: 'sseankrr' },
    { name: 'Mar', usn: 'mvrKa1' },
    { name: 'Dra ◇HIRTEAMWA', usn: 'durianspesial' },
    { name: 'Abian', usn: 'boycanada' },
    { name: 'ALVIC, باجينع', usn: 'idpenjjahat' },
    { name: 'Mahendra', usn: 'iParksange' },
    { name: 'Axel @SayangKanyelir', usn: 'weirdomo' },
    { name: 'JASPER. K ← // S\' JEVI', usn: 'iptangguh' },
    { name: 'Senon', usn: 'vienmad' },
    { name: '✿ . serene—kissed . Soren', usn: 'sorennis' },
    { name: 'Joel', usn: 'mocnks' },
    { name: 'Khalif', usn: 'sl1ck0' },
    { name: 'TANJIRO, Declan', usn: 'c4feracer1' },
    { name: 'ALASKA M.A', usn: 'kskahska' },
    { name: 'GALIH.', usn: 'MDXLIX' },
    { name: 'Leo', usn: 'kablteo' },
    { name: 'Amar', usn: 'theormos' },
    { name: 'ABIM', usn: 'iipeleerp' },
    { name: 'LUCIEN wschäl', usn: 'ph4win' },
    { name: 'GEWA', usn: 'rpepeex' },
    { name: 'Noel', usn: 'n0e1_0' },
    { name: 'Volkov', usn: 'xiaovenly' },
    { name: 'RAKHA ALTHARA', usn: 'rakhltar' },
    { name: 'bbvv ric', usn: 'hjhffvh' },
    { name: 'Nicholas.', usn: 'novcturnse' },
    { name: 'Junio P.', usn: 'Kkecelakaann' },
    { name: 'Devan', usn: 'wdymboi' },
    { name: 'Kendrick Mormont', usn: 'kendrickmorm' },
    { name: 'Heart\'s', usn: 'brokenheargted' },
    { name: 'fyinn.', usn: 'mentaliistic' },
    { name: 'Jackson.', usn: 'bBandarjudi' },
    { name: 'Jonathan @BolehHello', usn: 'kls9SD' },
    { name: 'Hussains', usn: 'Queell' },
    { name: 'Kai', usn: 'juhooncar' },
    { name: 'SOren? :3', usn: 'cuteneshs' },
    { name: 'Aven', usn: 'imiyeao' },
    { name: 'Keanu', usn: 'kenzccnteng' },
    { name: 'Sebastian', usn: 'chromososness' },
    { name: 'Miguel G.', usn: 'miguellgtg' },
    { name: 'جيرو', usn: 'Dffuly' },
    { name: 'Jay', usn: 'jayandexx' },
    { name: 'E. Arshaan Shailenda', usn: 'Hoovman' },
    { name: 'Glean', usn: 'gl3nx' },
    { name: '﹫; 𝓙eyummy. أبيض', usn: 'hyeonvx' },
    { name: '𝖤𝗆𝗆𝖺𝗇 تمام.', usn: 'rrqkink' },
    { name: '夜 pangestu wapo', usn: 'c4feracer1' },
    { name: 'Davlen', usn: 'BrngskBj' },
];

const FOTO_ANGGOTA = {
    AngPrata: './images/AngPrata.jpg',
    d1kalahujan: './images/d1kalahujan.jpg',
    gubergnurr: './images/gubergnurr.jpg',
    fuckpjuh: './images/fuckpjuh.jpg',
    Pfraksi: './images/Pfraksi.jpg',
    qampunhk: './images/qampunhk.jpg',
    snoopyeaye: './images/snoopyeaye.jpg',
    peng3dr: './images/peng3dr.jpg',
    siDaciL: './images/siDaciL.jpg',
    cpengocokk: './images/cpengocokk.jpg',
    qPrampok: './images/qPrampok.jpg',
    iCRlMlNAL: './images/iCRlMlNAL.jpg',
    cBastaard: './images/cBastaard.jpg',
    ruthIessx: './images/ruthIessx.jpg',
    Usrm4n: './images/Usrm4n.jpg',
    zydnll: './images/zydnll.jpg',
    Almondbabybigbboy: './images/Almondbabybigbboy.jpg',
    seanBandungb: './images/seanBandungb.jpg',
    grrydenn: './images/grrydenn.jpg',
    geminianjing: './images/geminianjing.jpg',
    bulvzit: './images/bulvzit.jpg',
    egysl: './images/egysl.jpg',
    ashotgaf: './images/ashotgaf.jpg',
    Nilhoov: './images/Nilhoov.jpg',
    Antiheruo: './images/Antiheruo.jpg',
    Jhncdne: './images/Jhncdne.jpg',
    seonghyeonreall: './images/seonghyeonreall.jpg',
    Lkomandann: './images/Lkomandann.jpg',
    Qbasict: './images/Qbasict.jpg',
    smotief: './images/smotief.jpg',
    iPejantanh: './images/iPejantanh.jpg',
    nerv_car: './images/nerv_car.jpg',
    fdeathsoul: './images/fdeathsoul.jpg',
    oAdorabble: './images/oAdorabble.jpg',
    afterhaz: './images/afterhaz.jpg',
    iPembelort: './images/iPembelort.jpg',
    NL0SH: './images/NL0SH.jpg',
    cSpawn: './images/cSpawn.jpg',
    ROOCKST14R: './images/ROOCKST14R.jpg',
    iLondonnn: './images/iLondonnn.jpg',
    jjshakel: './images/jjshakel.jpg',
    iLucied: './images/iLucied.jpg',
    Sceminar: './images/Sceminar.jpg',
    yeatao: './images/yeatao.jpg',
    angrybim: './images/angrybim.jpg',
    Presiden19: './images/Presiden19.jpg',
    wiLdercove: './images/wiLdercove.jpg',
    jvkEleon: './images/jvkEleon.jpg',
    iPec1ntaB0kp: './images/iPec1ntaB0kp.jpg',
    iCHOI_VJ: './images/iCHOI_VJ.jpg',
    yunhoimut: './images/yunhoimut.jpg',
    Chaotci: './images/Chaotci.jpg',
    wKonocortis: './images/wKonocortis.jpg',
    Dantelaso: './images/Dantelaso.jpg',
    Kafksamudra: './images/Kafksamudra.jpg',
    Religionistt: './images/Religionistt.jpg',
    tueelips: './images/tueelips.jpg',
    wbajar: './images/wbajar.jpg',
    iJeanaldrc: './images/iJeanaldrc.jpg',
    iPAnakBandung: './images/iPAnakBandung.jpg',
    tserpanah: './images/tserpanah.jpg',
    lLeviackermanx: './images/lLeviackermanx.jpg',
    sensadip: './images/sensadip.jpg',
    stxvey: './images/stxvey.jpg',
    ryxxan: './images/ryxxan.jpg',
    miloOkeandra: './images/miloOkeandra.jpg',
    niskasla: './images/niskasla.jpg',
    xmarllborro: './images/xmarllborro.jpg',
    vHotnive: './images/vHotnive.jpg',
    kael_ioo: './images/kael_ioo.jpg',
    Keonhju: './images/Keonhju.jpg',
    yagantebgg: './images/yagantebgg.jpg',
    pitobrengsek: './images/pitobrengsek.jpg',
    Kgntgan: './images/Kgntgan.jpg',
    papajahatgp3: './images/papajahatgp3.jpg',
    samuelxh: './images/samuelxh.jpg',
    ArrhamAli: './images/ArrhamAli.jpg',
    kntllbpkmu: './images/kntllbpkmu.jpg',
    kingzkale: './images/kingzkale.jpg',
    sghyeonZ: './images/sghyeonZ.jpg',
    retplak: './images/retplak.jpg',
    iNgaseng: './images/iNgaseng.jpg',
    zynczy: './images/zynczy.jpg',
    CAROLLUS: './images/CAROLLUS.jpg',
    mKayyes: './images/mKayyes.jpg',
    ssamuudraa: './images/ssamuudraa.jpg',
    hheatwavee: './images/hheatwavee.jpg',
    sseankrr: './images/sseankrr.jpg',
    mvrKa1: './images/mvrKa1.jpg',
    durianspesial: './images/durianspesial.jpg',
    boycanada: './images/boycanada.jpg',
    idpenjjahat: './images/idpenjjahat.jpg',
    iParksange: './images/iParksange.jpg',
    weirdomo: './images/weirdomo.jpg',
    iptangguh: './images/iptangguh.jpg',
    vienmad: './images/vienmad.jpg',
    sorennis: './images/sorennis.jpg',
    mocnks: './images/mocnks.jpg',
    sl1ck0: './images/sl1ck0.jpg',
    c4feracer1: './images/c4feracer1.jpg',
    kskahska: './images/kskahska.jpg',
    MDXLIX: './images/MDXLIX.jpg',
    kablteo: './images/kablteo.jpg',
    theormos: './images/theormos.jpg',
    iipeleerp: './images/iipeleerp.jpg',
    ph4win: './images/ph4win.jpg',
    rpepeex: './images/rpepeex.jpg',
    n0e1_0: './images/n0e1_0.jpg',
    xiaovenly: './images/xiaovenly.jpg',
    rakhltar: './images/rakhltar.jpg',
    hjhffvh: './images/hjhffvh.jpg',
    novcturnse: './images/novcturnse.jpg',
    Kkecelakaann: './images/Kkecelakaann.jpg',
    wdymboi: './images/wdymboi.jpg',
    kendrickmorm: './images/kendrickmorm.jpg',
    brokenheargted: './images/brokenheargted.jpg',
    mentaliistic: './images/mentaliistic.jpg',
    bBandarjudi: './images/bBandarjudi.jpg',
    kls9SD: './images/kls9SD.jpg',
    Queell: './images/Queell.jpg',
    juhooncar: './images/juhooncar.jpg',
    cuteneshs: './images/cuteneshs.jpg',
    imiyeao: './images/imiyeao.jpg',
    kenzccnteng: './images/kenzccnteng.jpg',
    chromososness: './images/chromososness.jpg',
    miguellgtg: './images/miguellgtg.jpg',
    Dffuly: './images/Dffuly.jpg',
    jayandexx: './images/jayandexx.jpg',
    Hoovman: './images/Hoovman.jpg',
    gl3nx: './images/gl3nx.jpg',
    hyeonvx: './images/hyeonvx.jpg',
    rrqkink: './images/rrqkink.jpg',
    BrngskBj: './images/BrngskBj.jpg',
};

/* ====== DATA PRIBADI perangkat ini (identitas, catatan usulan & pilihanmu) ====== */
function defaultMe() { return { myUsn: null, myNoms: [], myVotes: {} }; }
function loadMe() {
    try { const s = JSON.parse(localStorage.getItem(LS_KEY)); if (s) return Object.assign(defaultMe(), s); } catch (e) { }
    return defaultMe();
}
let state = loadMe();
function save() { try { localStorage.setItem(LS_KEY, JSON.stringify(state)); } catch (e) { } }

/* ====== HELPER ====== */
const memberByUsn = usn => ROSTER.find(m => m.usn === usn);
const memberName = usn => (memberByUsn(usn) || {}).name || usn || 'Anonim';
const catById = id => PUB.categories.find(c => c.id === id);
const candsIn = cat => Object.entries(PUB.candidates[cat] || {}).map(([id, n]) => ({ id, ...n }));
const allCands = () => PUB.categories.flatMap(c => candsIn(c.id));

/* ====== JADWAL TAHAPAN ====== */
const fmtDT = ts => ts ? new Date(ts).toLocaleString('id-ID', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—';
const phaseOpen = (s, e) => !!s && Date.now() >= s && (!e || Date.now() <= e);
const nomOpenNow = () => phaseOpen(PUB.nomStart, PUB.nomEnd);
const votingOpenNow = () => phaseOpen(PUB.voteStart, PUB.voteEnd);
const ts2input = ts => {
    if (!ts) return ''; const d = new Date(ts), p = n => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;
};